from infrastructure.repository1 import DepartmentsRepository, Departments
from infrastructure.repository2 import PatientRepository, Patients
from application.controller import Controller
from UI.console import UI
repo1 = DepartmentsRepository()
repo2 = PatientRepository()
ctrl = Controller(repo1, repo2)
patient1 = Patients("Jack", "Daniel", 1991115, "flu")
patient2 = Patients("Peter", "Sunny", 2657809, "ADHD")
patient3 = Patients("Angelina", "Mercy", 2090807, "flu")
patient4 = Patients("Joco", "Opra", 2578887, "Alzheimer")
patient5 = Patients("Alex", "Normand", 1009898, "flu")
patient6 = Patients("Thea", "Mico", 5890798, "ADHD")
repo2.add_patient(patient1)
repo2.add_patient(patient2)
repo2.add_patient(patient3)
repo2.add_patient(patient4)
repo2.add_patient(patient5)
repo2.add_patient(patient6)
department1 = Departments(1, "flu", 210)
department2 = Departments(2, "ADHD", 110)
department3 = Departments(3, "Alzheimer", 50)
department4 = Departments(4, "diabetes", 150)
repo1.add_department(department1)
repo1.add_department(department2)
repo1.add_department(department3)
repo1.add_department(department4)
ui = UI(ctrl)
ui.StartMenu()